version: '3.4'

services:
  wapproj2:
    image: wapproj2
    build:
      context: proj2
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8000:8000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.mjs"]
