version: '3.4'

services:
  wapproj2:
    image: wapproj2
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
